### ISSUE TITLE
Handle restore

### ISSUE THREAD

**Issue by jtpio** [vidartf/jupyterlab-kernelspy#12]
At the moment the `KernelSpyView` view is not restored on page reload.

![restore-widget](https://user-images.githubusercontent.com/591645/68863057-e1e3b080-06ee-11ea-8af4-3d66d0b37884.gif)

It would be great if it was, and would automatically reuse the same session!

**Comment by vidartf** [comment]
I agree, but note that this seems contradictory to #13.
