### ISSUE TITLE
Close the KernelSpyView on kernel shut down?

### ISSUE THREAD

**Issue by jtpio** [vidartf/jupyterlab-kernelspy#13]
Since the KernelSpyView is instantiated with a kernel, should the view be automatically be disposed when the kernel is shut down?

For example when going to running kernels tab and clicking on "Shut Down".

**Comment by jtpio** [comment]
> I think the current idea (though not fully implemented) was for it to track the notebook that started it (switch kernel when it switches).

Ah ok, then yes it wouldn't make sense.

But when the notebook is closed, then maybe the spy should also be closed?

**Comment by vidartf** [comment]
Yes, the "new kernel for notebook" function could add a listener for the "notebook closed" signal.
