### ISSUE TITLE
Kernel indicator

### ISSUE THREAD

**Issue by jtpio** [vidartf/jupyterlab-kernelspy#14]
When multiple KernelSpyView are opened, it can become difficult to remember which kernels they are using.

Maybe some indication (for example the path) in the toolbar could already help a bit?

![image](https://user-images.githubusercontent.com/591645/68863989-a77b1300-06f0-11ea-93c2-9618d6db4d2f.png)

**Comment by jtpio** [comment]
Or the session path? (for example `notebooks/Untitled.ipynb`)

**Comment by vidartf** [comment]
Currently the model takes a `Kernel.IKernel` argument (to make the minimum assumptions on the source of the kernel for maximum reusability). That object does not have access to the session path.

**Comment by jtpio** [comment]
Thanks @vidartf for the 2.0 update and the fixes!
