### ISSUE TITLE
Error during installation: Cannot find module 'jupyterlab-kernelspy/package.json'

### ISSUE THREAD

**Issue by dbrakman** [vidartf/jupyterlab-kernelspy#15]
From a computer running Ubuntu 16.04 with Jupyterlab v0.35.6, and Node v9.8.0, the installation command `jupyter labextension install jupyterlab-kernelspy` fails with:

```
/home/ubuntu/Python-3.7.3/share/jupyter/lab/staging/node_modules/webpack-cli/bin/cli.js:74
				throw err;
				^

Error: Cannot find module 'jupyterlab-kernelspy/package.json'
```

Have I missed a prerequisite installation step?

**Comment by vidartf** [comment]
It might be that there was an issue with the last release compatible with lab 0.35 (I don't really have time to troubleshoot this). I would strongly recommend updating to JupyterLab 1.0 though.

**Comment by dbrakman** [comment]
That solved my issue. Thanks!
(I also had to change my Node version to 6.*, 8.*, or >=10, per a helpful log message)
