### ISSUE TITLE
Switch to @types/react-inspector ?

### ISSUE THREAD

**Issue by jtpio** [vidartf/jupyterlab-kernelspy#9]
Types for `react-inspector` were recently published on npm: https://www.npmjs.com/package/@types/react-inspector

Maybe worth considering switching, although they don't seem to be exporting the `Theme` interface and appear less complete than https://github.com/vidartf/jupyterlab-kernelspy/blob/master/typings/react-inspector/react-inspector.d.ts

**Comment by vidartf** [comment]
I guess a decent resolution would be to upstream the typings to definitely typed.
